name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:
      run: make build
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name:
      run: make build-windows
